#!/usr/bin/env python2
# author : djunekz
# -*- coding: utf-8 -*-

from marshal import *
import os, sys
import fileinput

#color variable
N = '\033[0m'
D = '\033[90m'
W = '\033[1;37m'
B = '\033[1;34m'
R = '\033[1;31m'
G = '\033[1;32m'
Y = '\033[1;33m'
C = '\033[1;36m'
ask= G + '[' + W + 'Wallet' + G + ']'
que= G + '[' + W + 'Worker' + G + ']'
sukses= G + '[' + W + '!' + G + ']'
eror= R + '[' + W + '!' + R + ']'

os.system("clear")
print("""

\33[1;32m        ____  _____ ____  _____ \33[1;33m           _
\33[1;32m       |  _ \| ____|  _ \| ____|\33[1;33m _ __ ___ (_)_ __   ___ _ __
\33[1;32m       | |_) |  _| | |_) |  _|  \33[1;33m| '_ ` _ \| | '_ \ / _ \ '__|
\33[1;32m       |  __/| |___|  __/| |___ \33[1;33m| | | | | | | | | |  __/ |
\33[1;32m       |_|   |_____|_|   |_____|\33[1;33m|_| |_| |_|_|_| |_|\___|_|\33[0m

      \33[1;34m Author\33[1;36m :\33[1;33m D J U N E K Z
      \33[1;34m GitHub\33[1;36m :\33[1;33m https://github.com/djunekz/
      \33[1;34m Version\33[1;36m:\33[1;33m 1.0.0

       \33[1;31m [\33[1;36m Simple Tools for Mining Coin in Termux\33[1;31m ]
""")

banner2 = """
    {}[{}1{}]{} Start     {}[{}2{}]{} Registration     {}[{}3{}]{} Reset      {}[{}4{}]{} About
""".format(G,W,G,W,G,W,G,W,G,W,G,W,G,W,G,W)

print banner2

def reg():
   try:
       sc = raw_input(ask + W + " PEPE Wallet " + G + "> " + W)
       out = raw_input(que + W + " ID Worker " + G + " > " + W)
       os.system("cd usr/build && touch pepeminer && chmod +x pepeminer")
       os.system("cd usr/build && echo ./sh -o rx.unmineable.com:3333 -a randomx -u PEPE:" + sc + "." + out + "#tocl-x3k3 -p x -t 4 >> pepeminer")
       print (sukses + "Registration Successful...")
       os.system("sleep 2")
       os.system("python2 main")
   except KeyboardInterrupt:
       print (eror + " Stopped!")
   except IOError:
       print (eror + " Not Found!")

def start():
   try:
       print(" Please Wait...")
       os.system("sleep 3")
       os.system("cd usr/build && ./pepeminer")
   except KeyboardInterrupt:
       print (eror + " Stopped!")
   except IOError:
       print (eror + " Not Found!")

def res():
   try:
       os.system("cd usr/build && rm pepeminer")
       os.system("sleep 2")
       print(" Reset Account successful...")
   except KeyboardInterrupt:
       print (eror + " Stopped!")
   except IOError:
       print (eror + " Not Found!")

def abt():
   try:
       os.system("python2 bash")
   except KeyboardInterrupt:
       print (eror + " Stopped!")
   except IOError:
       print (eror + " Not Found!")

takok = raw_input(W + "Choose" + G + " > ")
if takok == "1" or takok == "01":
   start()
elif takok == "2" or takok == "02":
   reg()
if takok == "3" or takok == "03":
   res()
elif takok =="4" or takok == "04":
   abt()
if takok =="":
   print (eror + " Wrong input!")
   os.system("sleep 2")
   os.system("clear && python2 main")
