#!/usr/bin/env python2
# author : djunekz
# -*- coding: utf-8 -*-

from marshal import *
import os, sys
import fileinput

#color variable
N = '\033[0m'
D = '\033[90m'
W = '\033[1;37m'
B = '\033[1;34m'
R = '\033[1;31m'
G = '\033[1;32m'
Y = '\033[1;33m'
C = '\033[1;36m'
ask= G + '[' + W + 'Wallet' + G + ']'
que= G + '[' + W + 'Worker' + G + ']'
sukses= G + '[' + W + '!' + G + ']'
eror= R + '[' + W + '!' + R + ']'

os.system("clear")
print("""

\33[1;32m        ____  _____ ____  _____ \33[1;33m           _
\33[1;32m       |  _ \| ____|  _ \| ____|\33[1;33m _ __ ___ (_)_ __   ___ _ __
\33[1;32m       | |_) |  _| | |_) |  _|  \33[1;33m| '_ ` _ \| | '_ \ / _ \ '__|
\33[1;32m       |  __/| |___|  __/| |___ \33[1;33m| | | | | | | | | |  __/ |
\33[1;32m       |_|   |_____|_|   |_____|\33[1;33m|_| |_| |_|_|_| |_|\___|_|\33[0m

      \33[1;34m Author\33[1;36m :\33[1;33m D J U N E K Z
      \33[1;34m GitHub\33[1;36m :\33[1;33m https://github.com/djunekz/
      \33[1;34m Version\33[1;36m:\33[1;33m 1.0.0

       \33[1;31m [\33[1;36m Simple Tools for Mining Coin in Termux\33[1;31m ]
""")

banner2 = """
About:
{}+{} [{}>{}]{} Mining Monitor from Web : https://unmineable.com/address
{}+{} [{}>{}]{} Mining Monitor from App : unMineable [Playstore/AppStore]
{}+{} [{}>{}]{} Algorithm Pool          : RandomX XMRig
{}+{} [{}>{}]{} Author Mining for Termux: Djunekz

""".format(R,G,W,G,W,R,G,W,G,W,R,G,W,G,W,R,G,W,G,W)

print banner2
